# Configurations
title:            vdadh's blog
longtitle:        Jekyll Gitbook
author:           HE Tao
email:            2664158369@qq.com
description:      不正经人的一些臆语

version:          1.0
gitbook_version:  3.2.3

url:              'https://ifomo.github.io'
# baseurl:          '/jekyll-gitbook'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
# favicon_path:     /assets/gitbook/images/favicon.ico
# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://vdadh-picture-bed.oss-cn-hangzhou.aliyuncs.com/img/202307041609461.png
# favicon_path:    /assets/gitbook/images/202306042108061.png

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

################################################
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-RJEHFFJ5V9

# Gitalk
gitalk:
  clientID: 89044c6ac3e27e151918
  clientSecret: d3a1b9d7bd3b0ea7db9d5c1d6e6af3572f847049
  repo: ifomo.github.io
  owner: ifomo

# Pagination
paginate: 8

# 开启大纲列表？
# toc:
#     enabled: true

#文章私密访问
password: xzm1024
################################################

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
